apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zenvy-backend
  namespace: zenvy-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zenvy-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
    scaleDown:
      stabilizationWindowSeconds: 300

